### ISSUE TITLE
As a team we need to establish a clear procedure regarding our development process

### ISSUE THREAD

**Issue by HeorhiiS** [nyu-software-engineering/fall-2019-groceries#26]
- [x] User stories task extraction
- [x] Planning method
- [x] Standup schedule
- [x] Team norms
 
Discussion required

**Comment by asm-volatile** [comment]
What are your thoughts on the tasks that I extracted thus far in the Sprint 0 backlog? Tractable?

**Comment by HeorhiiS** [comment]
> What are your thoughts on the tasks that I extracted thus far in the Sprint 0 backlog? Tractable?

Yes, it is, but we have to move our tasks to planing poker as per requirements. I'll mark the task extraction.
